<?php

namespace IotExampleBundle\Repository;

/**
 * SensorsAndThreshHoldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorsAndThreshHoldsRepository extends \Doctrine\ORM\EntityRepository
{
}
